import type { Property } from "./property";
import type { CategorySlug } from "./categories";
import villa from "@/assets/hero-villa.jpg";
import home from "@/assets/cat-home.jpg";
import apt from "@/assets/cat-apartment.jpg";
import hostel from "@/assets/cat-hostel.jpg";
import land from "@/assets/cat-land.jpg";
import farm from "@/assets/cat-farmland.jpg";

export type { Property, Landmark } from "./property";
export { formatGHS, priceLabel } from "./property";

const cycle = [villa, apt, home, hostel, land, farm];
const galleryFor = (cover: string, n = 5) => {
  const others = cycle.filter((i) => i !== cover);
  return [cover, ...others.slice(0, n - 1)];
};

const landmarksAccra = [
  { name: "Ridge Hospital", kind: "Hospital", km: 1.4, mins: 6 },
  { name: "Achimota School", kind: "School", km: 3.1, mins: 12 },
  { name: "Accra Mall", kind: "Mall", km: 4.8, mins: 15 },
  { name: "Shell Fuel Station", kind: "Fuel", km: 0.6, mins: 3 },
  { name: "Stanbic Bank", kind: "Bank", km: 1.1, mins: 5 },
  { name: "Tetteh Quarshie Interchange", kind: "Transport", km: 2.4, mins: 8 },
  { name: "Holy Trinity Cathedral", kind: "Church", km: 1.8, mins: 7 },
];
const landmarksKumasi = [
  { name: "KNUST Main Gate", kind: "University", km: 2.2, mins: 9 },
  { name: "Komfo Anokye Hospital", kind: "Hospital", km: 3.5, mins: 14 },
  { name: "Kejetia Market", kind: "Market", km: 4.1, mins: 16 },
  { name: "Central Mosque", kind: "Mosque", km: 1.6, mins: 7 },
  { name: "Total Fuel Station", kind: "Fuel", km: 0.8, mins: 4 },
  { name: "Ecobank Adum", kind: "Bank", km: 2.0, mins: 8 },
];
const landmarksCoast = [
  { name: "University of Cape Coast", kind: "University", km: 1.2, mins: 5 },
  { name: "Cape Coast Castle", kind: "Landmark", km: 6.5, mins: 18 },
  { name: "Police Headquarters", kind: "Police", km: 2.1, mins: 8 },
  { name: "Cape Coast Hospital", kind: "Hospital", km: 2.9, mins: 10 },
];

export const properties: Property[] = [
  {
    id: "knust-hostel-suite",
    title: "KNUST Garden Hostel — Twin Suite",
    category: "hostels" as CategorySlug,
    city: "Kumasi",
    region: "Ashanti",
    neighborhood: "Ayeduase",
    priceGHS: 7200,
    priceUnit: "year",
    beds: 2, baths: 1,
    verified: true, featured: true, rating: 4.62, reviews: 58,
    cover: hostel, gallery: galleryFor(hostel),
    hostName: "Garden Halls", hostRole: "Hostel Manager",
    description: "Clean twin-share with study desk, fast Wi-Fi, kitchenette and 24-hour security. Five minutes from the KNUST main gate.",
    amenities: ["Wi-Fi", "24/7 security", "Study lounge", "Laundry", "Backup power"],
    coords: { lat: 6.6745, lng: -1.5716 },
    landmarks: landmarksKumasi,
  },
  {
    id: "legon-hostel-ensuite",
    title: "Legon Court Hostel — Single En-suite",
    category: "hostels" as CategorySlug,
    city: "Accra",
    region: "Greater Accra",
    neighborhood: "East Legon",
    priceGHS: 9600,
    priceUnit: "year",
    beds: 1, baths: 1,
    verified: true, featured: true, rating: 4.74, reviews: 96,
    cover: hostel, gallery: galleryFor(hostel),
    hostName: "Legon Court", hostRole: "Hostel Manager",
    description: "Private en-suite room a short shuttle from the University of Ghana. Reading room, borehole water and a fenced compound with gate security.",
    amenities: ["Wi-Fi", "En-suite bathroom", "Shuttle to campus", "Backup power", "Laundry"],
    coords: { lat: 5.6508, lng: -0.1869 },
    landmarks: landmarksAccra,
  },
  {
    id: "ucc-hostel-fourbed",
    title: "Amamoma Student Hostel — 4-in-a-Room",
    category: "hostels" as CategorySlug,
    city: "Cape Coast",
    region: "Central",
    neighborhood: "Amamoma",
    priceGHS: 4200,
    priceUnit: "year",
    beds: 4, baths: 1,
    verified: true, rating: 4.4, reviews: 71,
    cover: hostel, gallery: galleryFor(hostel),
    hostName: "Amamoma Halls", hostRole: "Hostel Manager",
    description: "Affordable four-in-a-room for UCC students, walking distance to the north campus gate. Prepaid meters, water storage tanks and a study balcony.",
    amenities: ["Wi-Fi", "Water storage", "Study balcony", "Security", "Prepaid meter"],
    coords: { lat: 5.1132, lng: -1.2905 },
    landmarks: landmarksCoast,
  },
  {
    id: "ridge-emerald-villa",
    title: "Emerald Ridge Villa with Infinity Pool",
    category: "homes" as CategorySlug,
    city: "Accra",
    region: "Greater Accra",
    neighborhood: "Cantonments",
    priceGHS: 28000,
    priceUnit: "month",
    beds: 5, baths: 6, area: "620 m²",
    verified: true, featured: true, rating: 4.96, reviews: 142,
    cover: villa, gallery: galleryFor(villa, 6),
    hostName: "Adwoa Mensah", hostRole: "Verified Landlord",
    description: "A serene hillside villa overlooking the Accra skyline. Floor-to-ceiling glass, infinity pool, full-staff quarters, and a chef's kitchen finished in Ghanaian hardwood.",
    amenities: ["Infinity pool", "Backup generator", "24/7 security", "Solar water", "Gardener", "Smart locks"],
    coords: { lat: 5.5694, lng: -0.1769 },
    landmarks: landmarksAccra,
  },
  {
    id: "east-legon-family-house",
    title: "3-Bedroom House for Rent, East Legon",
    category: "homes" as CategorySlug,
    city: "Accra",
    region: "Greater Accra",
    neighborhood: "East Legon",
    priceGHS: 14500,
    priceUnit: "month",
    beds: 3, baths: 3, area: "210 m²",
    verified: true, featured: true, rating: 4.88, reviews: 86,
    cover: apt, gallery: galleryFor(apt),
    hostName: "Kwame Asare", hostRole: "Agent · Heritage Realty",
    description: "Bright three-bedroom house with wrap-around balcony, mid-century African furnishings and views over East Legon's palm canopy.",
    amenities: ["Backup power", "Fitted kitchen", "Parking", "Air conditioning", "Gated"],
    coords: { lat: 5.6304, lng: -0.1597 },
    landmarks: landmarksAccra,
  },
  {
    id: "tema-family-home",
    title: "4-Bedroom Family House, Tema Comm. 25",
    category: "homes" as CategorySlug,
    city: "Tema",
    region: "Greater Accra",
    neighborhood: "Community 25",
    priceGHS: 9500,
    priceUnit: "month",
    beds: 4, baths: 4, area: "380 m²",
    verified: true, rating: 4.7, reviews: 24,
    cover: home, gallery: galleryFor(home),
    hostName: "Ama Owusu", hostRole: "Property Developer",
    description: "Newly built family home with terracotta tile roof, walled compound, mango trees and a paved driveway big enough for two SUVs.",
    amenities: ["Walled compound", "Gatehouse", "Borehole", "Solar geysers"],
    coords: { lat: 5.6839, lng: -0.0166 },
    landmarks: landmarksAccra,
  },
  {
    id: "kumasi-ahodwo-house",
    title: "2-Bedroom House for Rent, Ahodwo",
    category: "homes" as CategorySlug,
    city: "Kumasi",
    region: "Ashanti",
    neighborhood: "Ahodwo",
    priceGHS: 4800,
    priceUnit: "month",
    beds: 2, baths: 2, area: "120 m²",
    verified: true, rating: 4.61, reviews: 33,
    cover: home, gallery: galleryFor(home),
    hostName: "Selorm Adjei", hostRole: "Verified Landlord",
    description: "Quiet self-contained house on a tarred road in Ahodwo, with a shaded courtyard, borehole water and space for a small garden.",
    amenities: ["Borehole", "Courtyard", "Parking", "Prepaid meter"],
    coords: { lat: 6.6666, lng: -1.6295 },
    landmarks: landmarksKumasi,
  },
  {
    id: "takoradi-beach-house",
    title: "3-Bedroom House for Rent, Airport Ridge",
    category: "homes" as CategorySlug,
    city: "Takoradi",
    region: "Western",
    neighborhood: "Airport Ridge",
    priceGHS: 7600,
    priceUnit: "month",
    beds: 3, baths: 3, area: "240 m²",
    verified: true, rating: 4.55, reviews: 19,
    cover: villa, gallery: galleryFor(villa),
    hostName: "Heritage Realty", hostRole: "Agent",
    description: "Breezy family house on Airport Ridge with a covered veranda, mature coconut palms and a walled yard, minutes from the harbour road.",
    amenities: ["Veranda", "Walled yard", "Backup power", "Parking"],
    coords: { lat: 4.9016, lng: -1.7831 },
    landmarks: landmarksCoast,
  },
  {
    id: "aburi-hill-land",
    title: "1.2 Acre Hilltop Building Plot, Aburi",
    category: "lands" as CategorySlug,
    city: "Aburi",
    region: "Eastern",
    neighborhood: "Aburi Hills",
    priceGHS: 420000,
    priceUnit: "total",
    area: "4,856 m²",
    verified: true, featured: true, rating: 4.5, reviews: 11,
    cover: land, gallery: galleryFor(land),
    hostName: "Kojo Annan", hostRole: "Land Agent",
    description: "Surveyed and registered hilltop plot with cool mountain air and views toward the Accra plains. Suitable for a private estate or boutique retreat.",
    amenities: ["Surveyed", "Title documents", "Road access"],
    coords: { lat: 5.85, lng: -0.1741 },
    landmarks: [
      { name: "Aburi Botanical Gardens", kind: "Landmark", km: 1.0, mins: 4 },
      { name: "Peduase Police Post", kind: "Police", km: 3.2, mins: 9 },
      { name: "Aburi Girls' SHS", kind: "School", km: 1.6, mins: 6 },
      { name: "Total Fuel Station", kind: "Fuel", km: 2.1, mins: 7 },
    ],
  },
  {
    id: "oyibi-building-plot",
    title: "Registered Building Plot, Oyibi",
    category: "lands" as CategorySlug,
    city: "Oyibi",
    region: "Greater Accra",
    neighborhood: "Oyibi",
    priceGHS: 185000,
    priceUnit: "total",
    area: "600 m²",
    verified: true, rating: 4.42, reviews: 8,
    cover: land, gallery: galleryFor(land),
    hostName: "Nii Armah", hostRole: "Land Agent",
    description: "Litigation-free plot with indenture and site plan, on a graded access road close to Valley View University. Ready to build.",
    amenities: ["Indenture", "Site plan", "Graded road", "Electricity nearby"],
    coords: { lat: 5.7519, lng: -0.0546 },
    landmarks: landmarksAccra,
  },
  {
    id: "ejisu-storage-yard-land",
    title: "Half-Acre Yard for Rent, Ejisu Roadside",
    category: "lands" as CategorySlug,
    city: "Ejisu",
    region: "Ashanti",
    neighborhood: "Ejisu",
    priceGHS: 2600,
    priceUnit: "month",
    area: "2,023 m²",
    verified: true, rating: 4.3, reviews: 6,
    cover: land, gallery: galleryFor(land),
    hostName: "Nana Yaw", hostRole: "Land Owner",
    description: "Flat roadside parcel available for monthly hire — suited to a builder's yard, block factory or storage, with wide truck access.",
    amenities: ["Truck access", "Fenced", "Roadside frontage"],
    coords: { lat: 6.7402, lng: -1.4533 },
    landmarks: landmarksKumasi,
  },
  {
    id: "ejisu-cocoa-farm",
    title: "18-Acre Cocoa Farm Land, Ejisu",
    category: "farmlands" as CategorySlug,
    city: "Ejisu",
    region: "Ashanti",
    neighborhood: "Ejisu",
    priceGHS: 980000,
    priceUnit: "total",
    area: "72,843 m²",
    verified: true, featured: true, rating: 4.8, reviews: 9,
    cover: farm, gallery: galleryFor(farm),
    hostName: "Nana Yaw", hostRole: "Farm Owner",
    description: "Producing cocoa farm with mature trees, red dirt access roads and a small farmhouse. Available for purchase or seasonal hire.",
    amenities: ["Mature trees", "Farmhouse", "Borehole", "Storage shed"],
    coords: { lat: 6.7402, lng: -1.4533 },
    landmarks: landmarksKumasi,
  },
  {
    id: "afram-plains-farmland",
    title: "25-Acre Arable Farm Land for Hire, Afram Plains",
    category: "farmlands" as CategorySlug,
    city: "Donkorkrom",
    region: "Eastern",
    neighborhood: "Afram Plains",
    priceGHS: 18000,
    priceUnit: "year",
    area: "101,171 m²",
    verified: true, rating: 4.6, reviews: 7,
    cover: farm, gallery: galleryFor(farm),
    hostName: "Afram Agro", hostRole: "Farm Manager",
    description: "Cleared arable land for seasonal hire — maize, yam and vegetable ready, with irrigation access from the Volta and a caretaker on site.",
    amenities: ["Cleared land", "Irrigation access", "Caretaker", "Tractor access"],
    coords: { lat: 6.6667, lng: -0.0667 },
    landmarks: [
      { name: "Donkorkrom Market", kind: "Market", km: 5.0, mins: 14 },
      { name: "Donkorkrom Hospital", kind: "Hospital", km: 6.2, mins: 18 },
      { name: "Volta Ferry Landing", kind: "Transport", km: 9.0, mins: 25 },
    ],
  },
];

export const regions = [
  { name: "Greater Accra", count: 482, image: "/regions/accra" },
  { name: "Ashanti", count: 318, image: "/regions/kumasi" },
  { name: "Central", count: 164, image: "/regions/capecoast" },
  { name: "Western", count: 121, image: "/regions/takoradi" },
];

export function getProperty(id: string) {
  return properties.find((p) => p.id === id);
}
